name: Manual zip WordPress plugin

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  zip-plugin:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
          
      # Upload ZIP file as an artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.PLUGIN_FOLDER_NAME }}-v${{ github.ref_name}}
          path: /home/runner/work/${{ vars.PLUGIN_FOLDER_NAME }}/
          retention-days: 3