name: Manual zip WordPress plugin

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  zip-plugin:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create a temporary directory for the plugin
      - name: Create plugin directory structure
        run: |
          mkdir -p .build/${{ vars.PLUGIN_FOLDER_NAME }}
          
      # Copy plugin files (excluding development files)
      - name: Copy plugin files
        run: |
          # Copy all files except those listed in .distignore
          rsync -r \
            --exclude-from=.distignore \
            --exclude='.*' \
            . .build/${{ vars.PLUGIN_FOLDER_NAME }}/

      # Create ZIP file
      - name: Create ZIP file
        run: |
          cd .build
          zip -r ${{ vars.PLUGIN_FOLDER_NAME }}-v${{ github.ref_name}}.zip ${{ vars.PLUGIN_FOLDER_NAME }}

      # Upload ZIP file as a workflow artifact
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.PLUGIN_FOLDER_NAME }}-v${{ github.ref_name}}.zip
          path: .build/${{ vars.PLUGIN_FOLDER_NAME }}-v${{ github.ref_name}}.zip
          retention-days: 3
